<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="Author" content="Swaraj Dutta" />
    <link rel="stylesheet" type="text/css" href="assets/css/style.css" />
    <link rel="stylesheet" type="text/css" href="assets/css/style1.css" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@300&display=swap" rel="stylesheet" />

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous" />

    <title>NoMad</title>
</head>

<body data-spy="scroll" data-target=".navbar" data-offset="50">
    <?php include 'navbar.php'; ?>
    <br><br><br>
    <!-- Terms & Conditions -->
    <div class="container-fluid text-center">
        <h3>Terms and Conditions</h3>
        <p>This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as
            applicable and the amended provisions pertaining to electronic records in various statutes as amended by the
            Information Technology Act, 2000. This electronic record is generated by a computer system and does not
            require any physical or digital signatures.</p><br>
        <p>Introduction
            Welcome to www.bikersclub.in services, provided by Bikers Club Network Private Limited (A Company
            incorporated under the Companies Act, 2013). Wherever the term "BIKERS CLUB ®" or “BC” or "BIKERS CLUB ®
            NETWORK" or "bikersclub.in" or "www.bikersclub.in" or "www.bikersclub.in/online-store" is used it refers to
            Bikers Club Network Private Limited, and its subsidiaries, controlled entities, affiliates and related
            parties. The terms and conditions contained herein along with the Privacy Policy and the Returns Policy form
            an Agreement regulating our relationship with regards to the use of www.bikersclub.in services by you. You
            are advised to read this Agreement carefully. If you are not agreeable to any terms and conditions or
            Privacy Policy, you should not use this service. You can use www.bikersclub.in services, if you are
            agreeable to all the terms and conditions of this Agreement in their entirety. If you accept this agreement,
            it will be a legally binding agreement between you and Bikers Club Network Private Limited.


            All products/services and information displayed on www.bikersclub.in ("Site" or "Website") constitute an
            "invitation to offer". Your order for purchase constitutes your "offer" which shall be subject to the terms
            and conditions as listed below. www.bikersclub.in reserves the right to accept or reject your offer. If you
            have supplied us with your email address, we will notify you by email as soon as possible to confirm receipt
            of your order. Our acceptance of your order will take place upon dispatch of the product(s) ordered. No act
            or omission of www.bikersclub.in prior to the actual dispatch of the product (s) ordered will constitute
            acceptance of your offer.

            ​

            Membership Eligibility


            Use of the Site is available only to persons who can form legally binding contracts under applicable law.
            Persons who are "incompetent to contract" within the meaning of the Indian Contract Act, 1872 including
            un-discharged insolvents etc. are not eligible to use the Site. If you are a minor i.e. under the age of 18
            years but at least 13 years of age you may use this Site only under the supervision of a parent or legal
            guardian who agrees to be bound by these Terms of Use. If your age is below that of 18 years your parents or
            legal guardians can transact on behalf of you if they are registered users. You are prohibited from
            purchasing any material which is for adult consumption the sale or purchase of which to/by minors is
            strictly prohibited. www.bikersclub.in reserves the right to terminate your membership and refuse to provide
            you with access to the Site if www.bikersclub.in discovers that you are under the age of 18 years. The Site
            is not available to persons whose membership has been suspended or terminated by www.bikersclub.in for any
            reason whatsoever. If you are registering as a business entity, you represent that you have the authority to
            bind the entity to this User Agreement.


            Unless otherwise specified, the materials on this website are directed solely at those who consume the
            materials within India. www.bikersclub.in makes no representation that any products or services referred to
            in the materials on this website are appropriate for use or available outside India. Those who choose to
            access this Site from outside India are responsible for compliance with local laws if and to the extent
            local laws are applicable. www.bikersclub.in will deliver the products only within India and will not be
            liable for any claims relating to any products ordered from outside India.


            Except where additional terms and conditions are provided which are product specific, these terms and
            conditions supersede all previous representations, understandings, or agreements and shall prevail
            notwithstanding any variance with any other terms of any order submitted. By using the services of
            www.bikersclub.in you agree to be bound by the Terms and Conditions.

            ​

            Governing Law and Jurisdiction


            This Agreement shall be construed in accordance with the applicable laws of India. The Courts at Mumbai
            shall have exclusive jurisdiction in any proceedings arising out of this agreement.

            ​

            Account and Registration Obligations


            "Your Information" is defined as any information you provide to us in the registration, buying or listing
            process, in the feedback area or through any e-mail feature. We will protect Your Information in accordance
            with our Privacy Policy. If you use the Site, you shall be responsible for maintaining the confidentiality
            of your account and password and for restricting access to your computer, and you agree to accept
            responsibility for all activities that occur under your account or password. www.bikersclub.in shall not be
            liable to any person for any loss or damage which may arise as a result of any failure by you to protect
            your password or account. If you know or suspect that someone else knows your password you should notify us
            by contacting us immediately through the address provided below. If www.bikersclub.in has reason to believe
            that there is likely to be a breach of security or misuse of the www.bikersclub.in Site, we may require you
            to change your password or we may suspend your account without any liability cast upon www.bikersclub.in

            ​

            You also agree to:

            Provide true, accurate, current and complete information about yourself as prompted by www.bikersclub.in’s
            registration form (such information being given in the "New User Register Information and Profile
            Information")

            Maintain and promptly update the Profile information to keep it true, accurate, current and complete. If you
            provide any information that is untrue, inaccurate, incomplete, or not current or if www.bikersclub.in has
            reasonable grounds to suspect that such information is untrue, inaccurate and not current or not in
            accordance with the User Agreement, www.bikersclub.in has the right to indefinitely suspend or terminate
            your membership and refuse to provide you with access to the Site.

            ​

            Pricing Information


            While www.bikersclub.in strives to provide accurate product and pricing information, pricing errors or
            typographical errors may occur. www.bikersclub.in cannot confirm the price of a product until after you
            order. In the event that a product is listed at an incorrect price or with incorrect information due to an
            error in pricing or product information, www.bikersclub.in shall have the right, at our sole discretion, to
            refuse or cancel any orders placed for that product, unless the product has already been dispatched. In the
            event that an item carries an incorrect price, www.bikersclub.in may, at its discretion, either contact you
            for instructions or cancel your order and notify you of such cancellation. Unless the product ordered by you
            has been dispatched, your offer will not be deemed accepted/confirmed and www.bikersclub.in will have the
            right to modify the price of the product and contact you for further instructions using the e-mail address
            or phone number provided by you during the time of registration, or cancel the order and notify you of such
            cancellation. In the event that www.bikersclub.in accepts your order the same shall be debited from your
            debit/credit card account and duly notified to you by email that the payment has been processed. The payment
            may be processed prior to www.bikersclub.in dispatch of the product that you have ordered. If we have to
            cancel the order after we have processed the payment, the said amount will be reversed back to your
            debit/credit card account.

            ​

            Order Cancellations


            There may be certain orders that we are unable to confirm/accept and must cancel. We reserve the right, at
            our sole discretion, to refuse or cancel any order for any reason. Some situations that may result in your
            order being cancelled include limitations on quantities available for purchase, inaccuracies or errors in
            product or pricing information, or problems identified by our debit/credit and fraud avoidance department.
            We may also require additional verifications or information before confirming/accepting any order. We will
            contact you if all or any portion of your order is cancelled or if additional information is required to
            accept your order. If your order is cancelled after your debit/credit card has been charged, the said amount
            will be reversed back in your Card Account.

            ​

            Cancellations by the customer


            In case we receive a cancellation notice and the order has not been processed/approved by us, we shall
            cancel the order and refund the entire amount. On cancellation of an order, after it has been
            processed/approved by www.bikersclub.in, the cancellation charges will become applicable @ flat rate of 5%
            of the order value.www.bikersclub.in has the full right to decide whether an order has been processed or
            not. The customer agrees not to dispute the decision made by www.bikersclub.in and accept
            www.bikersclub.in’s decision regarding the cancellation.

            ​</p>
    </div>
    <?php include 'footer.php'; ?>
    <script src="https://kit.fontawesome.com/0dc3a790fc.js" crossorigin="anonymous"></script>
    <script src="assets/js/script.js"></script>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>

</body>

</html>